version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
      args:
        - DOMAIN=$DOMAIN
    env_file:
       - .env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/
    depends_on:
      wordpress:
        condition: service_healthy
    restart: on-failure
    networks:
      - customNetwork

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      args:
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_PASSWORD_ROOT=$DB_PASSWORD_ROOT
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    networks:
      - customNetwork

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
    volumes:
      - wordpress:/var/www/
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure
    healthcheck:
      test: ["CMD", "cat", "/var/www/wordpress/wp-config.php"]
      interval: 5s
      retries: 25
    networks:
      - customNetwork
    
volumes:
  wordpress:
    driver_opts:
      type: "none"
      o: "bind"
      device: /home/ebillon/data/wordpress
  mariadb:
    driver_opts:
      type: "none"
      o: "bind"
      device: /home/ebillon/data/mariadb

networks:
  customNetwork:
    driver: bridge